kind: Deployment
apiVersion: apps/v1
metadata: 
   name: deploypod
spec: 
   replicas: 2
   selector:
     matchLabels: 
       name: deployment
   template:
       metadata:
         labels: 
          name: deployment
       spec: 
         containers: 
           - name: c00
             image: httpd
             ports:
                - containerPort: 80

