kind: Pod
apiVersion: v1
metadata: 
    name: mypod
spec: 
  containers: 
     - name: c00
       image: centos
       command: ["/bin/bash", "-c", "while true; do echo jyo; sleep 5 ; done"]
       volumeMounts:
          - name: podvol
            mountPath: "/tmp/c1dir"
     - name: c01
       image: centos
       command: ["/bin/bash", "-c", "while true; do echo jyo; sleep 5 ; done"]
       volumeMounts: 
          - name: podvol
            mountPath: "/tmp/c2dir"
  volumes:
       - name: podvol
         emptyDir: {}
