kind: Pod
apiVersion: v1
metadata: 
 name: testpod
spec:
  containers: 
     - name: c00
       image: ubuntu
       command: ["/bin/bash", "-c", "while true; do echo jyo; sleep 5 ; done"]

     - name: c01
       image: centos
       command: ["/bin/bash", "-c", "while true; do echo jyo; sleep 5 ; done"]
