kind: Pod
apiVersion: v1
metadata: 
  name: nodepod
spec: 
  containers: 
    - name: c00
      image: centos
      command: ["/bin/bash", "-c", "while true; do echo jyo; sleep 5 ; done"]
  nodeSelector: 
     mynode: testing 
