kind: Pod
apiVersion: v1
metadata:
  name: pod1
  annotations:
    describe: my testpod
spec: 
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo jyo; sleep 5 ; done"]
