kind: ReplicationController
apiVersion: v1
metadata: 
  name: replicationcontroller
spec: 
   replicas: 2
   selector: 
     myname: sai
   template:   
     metadata: 
       labels:
         myname: sai
     spec: 
       containers: 
          - name: c00
            image: ubuntu
            command: ["/bin/bash", "-c", "while true; do echo jyo; sleep 5 ; done"]

      
